# 代码生成器配置
output_dir: "generated"
template_dir: "templates"
enable_field_encryption: false
field_encryption_salt: "my_salt"
excluded_types:
  - "FILE"
  - "va_list"
type_mappings:
  "uint8_t": "unsigned char"
  "int32_t": "int" 