default:
  handlers:
    console:
      format: "<green>{time:YYYY-MM-DD HH:mm:ss}</green> | <level>{level: <8}</level> | <cyan>{name}</cyan>:<cyan>{function}</cyan>:<cyan>{line}</cyan> - <level>{message}</level>"
      level: INFO
      colorize: true
    
    file:
      format: "{time:YYYY-MM-DD HH:mm:ss} | {level: <8} | {name}:{function}:{line} - {message}"
      level: DEBUG
      rotation: "1 day"
      retention: "30 days"
      compression: "zip"

development:
  handlers:
    console:
      level: DEBUG
    file:
      path: "logs/dev.log"

production:
  handlers:
    console:
      level: WARNING
    file:
      path: "logs/prod.log" 