# 日志配置
log_level: DEBUG
log_file: logs/app.log
format: "{time:YYYY-MM-DD HH:mm:ss} | {level: <8} | {name: <15} | {message}"
rotation: "1 day"
retention: "7 days"
compression: "zip"
backtrace: true
diagnose: true
enqueue: true 